### ISSUE TITLE
templateflow issue with singularity 

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_auto_qc#28]
When I use [this](https://github.com/SIMEXP/giga_preprocess2/blob/cobre/cobre/submit_qc.sh) script to run the auto_qc with the singularity image I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/giga_auto_qc", line 8, in <module>
    sys.exit(main())
  File "/code/giga_auto_qc/run.py", line 83, in main
    workflow(args)
  File "/code/giga_auto_qc/workflow.py", line 65, in workflow
    ) = assessments.get_reference_mask(
  File "/code/giga_auto_qc/assessments.py", line 58, in get_reference_mask
    import templateflow
  File "/usr/local/lib/python3.9/site-packages/templateflow/__init__.py", line 31, in <module>
    update(local=True, overwrite=False, silent=True)
  File "/usr/local/lib/python3.9/site-packages/templateflow/conf/__init__.py", line 77, in update
    success = _update_s3(TF_HOME, local=local, overwrite=overwrite, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/templateflow/conf/_s3.py", line 20, in update
    retval = _update_skeleton(skel_file, dest, overwrite=overwrite, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/templateflow/conf/_s3.py", line 70, in _update_skeleton
    zipref.extractall(str(dest), members=newfiles)
  File "/usr/local/lib/python3.9/zipfile.py", line 1642, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.9/zipfile.py", line 1696, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 30] Read-only file system: '/templateflow/tpl-MouseIn/tpl-MouseIn_res-2_T1map.nii.gz'
```

If I try binding a writeable templateflow path using `-B ${HOME}/.cache/templateflow:/templateflow` then I get the same anatomical dice error as [here](https://github.com/SIMEXP/giga_auto_qc/issues/19#issuecomment-1697622561). So maybe that was causing that error somehow.

Any ideas how I can deal with this @htwangtw (or @Hyedryn?) Thank you!

**Comment by htwangtw** [comment]
yep this is an annoying known issue when using docker read-only setting.
Templateflow will index everything, no matter what :/
I should have suspected this issue as singularity/apptainer is by default read-only.
I did not set the dockerfile to allow user binding the `templateflow/` directory.

Solutions:
1. try `--writable-tmpfs`. See explaination [here](https://docs.sylabs.io/guides/3.5/user-guide/persistent_overlays.html)
2. I will look into how to let user bind a directory in this case...

**Comment by clarkenj** [comment]
I see, thank you, I'll try number 1!

**Comment by clarkenj** [comment]
After adding `--writable-tmpfs` I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/giga_auto_qc", line 8, in <module>
    sys.exit(main())
  File "/code/giga_auto_qc/run.py", line 83, in main
    workflow(args)
  File "/code/giga_auto_qc/workflow.py", line 65, in workflow
    ) = assessments.get_reference_mask(
  File "/code/giga_auto_qc/assessments.py", line 58, in get_reference_mask
    import templateflow
  File "/usr/local/lib/python3.9/site-packages/templateflow/__init__.py", line 31, in <module>
    update(local=True, overwrite=False, silent=True)
  File "/usr/local/lib/python3.9/site-packages/templateflow/conf/__init__.py", line 77, in update
    success = _update_s3(TF_HOME, local=local, overwrite=overwrite, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/templateflow/conf/_s3.py", line 20, in update
    retval = _update_skeleton(skel_file, dest, overwrite=overwrite, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/templateflow/conf/_s3.py", line 70, in _update_skeleton
    zipref.extractall(str(dest), members=newfiles)
  File "/usr/local/lib/python3.9/zipfile.py", line 1642, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.9/zipfile.py", line 1696, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 61] No data available: '/templateflow/tpl-MouseIn/tpl-MouseIn_res-2_T1map.nii.gz'
```

:sob:

**Comment by htwangtw** [comment]
Okay I will have to allow mounting a templateflow directory to fix this.

Meanwhile, install the library in an isolated virtual environment is the only way to go. 
If you can resolve this issue it will be a huge deal, since it requires understanding how path and environment works, which is 90% of the reason that I have seen when people said *the code is not working*.
