### ISSUE TITLE
error on fmriprep output with anatomical fast-track

### ISSUE THREAD

**Issue by bpinsard** [SIMEXP/giga_auto_qc#32]
```
Retrieved anatomical reference mask
Use standard template as functional scan reference.
Calculate the anatomical dice score.
  0%|                                                                                                                 | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data3.10/bin/giga_auto_qc", line 8, in <module>
    sys.exit(main())
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data3.10/lib/python3.10/site-packages/giga_auto_qc/run.py", line 83, in main
    workflow(args)
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data3.10/lib/python3.10/site-packages/giga_auto_qc/workflow.py", line 69, in workflow
    anatomical_metrics = assessments.calculate_anat_metrics(
  File "/lustre03/project/6003287/bpinsard/.virtualenvs/neuromod_data3.10/lib/python3.10/site-packages/giga_auto_qc/assessments.py", line 351, in calculate_anat_metrics
    anat_dice = _dice_coefficient(anat_image[0], reference_masks["anat"])
IndexError: list index out of range
```

**Comment by htwangtw** [comment]
This is likely due to unsuccessful attempt of creating a BIDS dataset index. 
Solution: 
- raise error when the BIDS layout object is empty
- better error message to help debugging

**Comment by clarkenj** [comment]
@htwangtw I am getting a similar error for prisme:

```
Retrieved anatomical reference mask
Create dataset level functional brain mask
We found 1 unique affine matrices. The most common one is [[   2.     0.     0.   -96.5]
 [   0.     2.     0.  -132.5]
 [   0.     0.     2.   -78.5]
 [   0.     0.     0.     1. ]]
Calculate the anatomical dice score.
^M  0%|          | 0/25 [00:00<?, ?it/s]^M  0%|          | 0/25 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/giga_auto_qc", line 8, in <module>
    sys.exit(main())
  File "/code/giga_auto_qc/run.py", line 83, in main
    workflow(args)
  File "/code/giga_auto_qc/workflow.py", line 69, in workflow
    anatomical_metrics = assessments.calculate_anat_metrics(
  File "/code/giga_auto_qc/assessments.py", line 351, in calculate_anat_metrics
    anat_dice = _dice_coefficient(anat_image[0], reference_masks["anat"])
IndexError: list index out of range
```

Is there a way around it?

**Comment by htwangtw** [comment]
Can you give me the file names in the subject directory?

**Comment by clarkenj** [comment]
Ah so this may be the problem, there is no `anat` directory... An example subject (with just one session):

```
├── sub-530814
   │   ├── ses-01
   │   │   ├── func
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-06_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_from-T1w_to-scanner_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_desc-confounds_timeseries.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_space-fsLR_den-91k_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-08_part-mag_space-T1w_desc-preproc_bold.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_from-scanner_to-T1w_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-MNI152NLin2009cAsym_desc-aparcaseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_desc-confounds_timeseries.tsv
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-03_part-mag_space-T1w_desc-preproc_bold.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-02_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_part-mag_space-T1w_desc-brain_mask.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-07_part-mag_space-T1w_desc-brain_mask.json
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-01_space-fsLR_den-91k_bold.dtseries.nii
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_from-scanner_to-boldref_mode-image_xfm.txt
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-04_part-mag_space-T1w_boldref.nii.gz
   │   │   │   ├── sub-530814_ses-01_task-prisme_dir-PA_run-05_part-mag_space-MNI152NLin2009cAsym_desc-preproc_bold.json
   │   │   ├── fmap
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun08_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun07_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun06_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun06_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun07_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun07_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun03_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_run-01_fmapid-sub530814ses01taskprismedirPArun01_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun07_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun06_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun05_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun06_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun04_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_run-01_fmapid-sub530814ses01taskprismedirPArun01_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun02_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun04_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun05_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun05_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun04_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_run-01_fmapid-sub530814ses01taskprismedirPArun01_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun08_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun04_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun03_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun02_desc-preproc_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun08_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun08_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun03_desc-preproc_fieldmap.json
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun02_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun03_desc-coeff_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun05_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_run-01_fmapid-sub530814ses01taskprismedirPArun01_desc-magnitude_fieldmap.nii.gz
   │   │   │   ├── sub-530814_ses-01_fmapid-sub530814ses01taskprismedirPArun02_desc-preproc_fieldmap.json
```

**Comment by htwangtw** [comment]
this explains things! I will work on a fix while compute canada is down and make sure you can run this as soon as they are back online

**Comment by clarkenj** [comment]
TYSM!
